/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuklidtransfertime;

import java.awt.BorderLayout;
import java.awt.ComponentOrientation;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Cell;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.apache.poi.EncryptedDocumentException;
import static org.apache.poi.hssf.usermodel.HeaderFooter.date;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author Acer
 */
public class nuklidTransferTime extends javax.swing.JFrame {
    stopWatch stopwatch = new stopWatch();
    private double elapsedTime;
    private Object textarea;
    public File file;
    public String target = "";
    public String row;
    public String formattedTime;
    private Boolean emptySheet = false;
    //public String path = "\\\\vgregion.se\\Hem\\SU-008\\olojo5\\Mina dokument\\temp.txt";//default path for file if no other is chosen
    //public String path = "G:\\\\SU.Omr4.MFT.Radiofarmakacentralen\\\\Utrustning\\\\PETtrace 880\\\\Ledningar\\\\Transfertid\\\\transferTime.txt";//default path for file if no other is chosen
    public String path = "C:\\temp\\output.xlsx";
    /**
     * Creates new form nuklidTransferTime
     */
    public nuklidTransferTime() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStartStop = new javax.swing.ButtonGroup();
        fileBrowser = new javax.swing.JFileChooser();
        buttonGroupCheckBox = new javax.swing.ButtonGroup();
        startButton = new javax.swing.JToggleButton();
        stopButton = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPaneElapsedTime = new javax.swing.JTextPane();
        labelInfo = new javax.swing.JLabel();
        jCheckBoxT1 = new javax.swing.JCheckBox();
        jCheckBoxT2 = new javax.swing.JCheckBox();
        jCheckBoxT4 = new javax.swing.JCheckBox();
        jCheckBoxEmpty = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuBarFile = new javax.swing.JMenu();
        menuBarFileItemBrowsefile = new javax.swing.JMenuItem();
        menuBarFileAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuklid transfer time");
        setBackground(new java.awt.Color(51, 255, 51));
        setResizable(false);

        buttonGroupStartStop.add(startButton);
        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startButtonMousePressed(evt);
            }
        });

        buttonGroupStartStop.add(stopButton);
        stopButton.setText("Stop");
        stopButton.setMaximumSize(new java.awt.Dimension(57, 23));
        stopButton.setMinimumSize(new java.awt.Dimension(57, 23));
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stopButtonMousePressed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textPaneElapsedTime.setToolTipText("");
        textPaneElapsedTime.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jScrollPane2.setViewportView(textPaneElapsedTime);

        buttonGroupCheckBox.add(jCheckBoxT1);
        jCheckBoxT1.setText("T1 F18");
        jCheckBoxT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxT1ActionPerformed(evt);
            }
        });

        buttonGroupCheckBox.add(jCheckBoxT2);
        jCheckBoxT2.setText("T2 N13");
        jCheckBoxT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxT2ActionPerformed(evt);
            }
        });

        buttonGroupCheckBox.add(jCheckBoxT4);
        jCheckBoxT4.setText("T4 F18");
        jCheckBoxT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxT4ActionPerformed(evt);
            }
        });

        buttonGroupCheckBox.add(jCheckBoxEmpty);
        jCheckBoxEmpty.setText("N/A");
        jCheckBoxEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEmptyActionPerformed(evt);
            }
        });

        jLabel1.setText("Target:");

        menuBarFile.setText("File");

        menuBarFileItemBrowsefile.setText("Select log file");
        menuBarFileItemBrowsefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarFileItemBrowsefileActionPerformed(evt);
            }
        });
        menuBarFile.add(menuBarFileItemBrowsefile);

        menuBarFileAbout.setText("About");
        menuBarFileAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarFileAboutActionPerformed(evt);
            }
        });
        menuBarFile.add(menuBarFileAbout);

        menuBar.add(menuBarFile);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxT1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxT2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxT4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxEmpty)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxT1)
                    .addComponent(jCheckBoxT2)
                    .addComponent(jCheckBoxT4)
                    .addComponent(jCheckBoxEmpty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMousePressed
        textPaneElapsedTime.setText("Counting");
        stopwatch.start();
        labelInfo.setText("");
        //System.out.println("Startbutton...");
    }//GEN-LAST:event_startButtonMousePressed

    private void stopButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMousePressed
        elapsedTime = stopwatch.elapsedTime();
        StyledDocument doc = textPaneElapsedTime.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        if(elapsedTime>0){
        formattedTime = String.format("%.1f",elapsedTime);
        textPaneElapsedTime.setText(formattedTime+"s");
        FileWriter fileWriter;
        
        try {
            Date date = new Date();
            row = (target+";"+date.toString()+";"+formattedTime+"\n");
            FileInputStream inputStream = new FileInputStream(new File(path));
            Workbook workbook = WorkbookFactory.create(inputStream);
 
            Sheet sheet = workbook.getSheetAt(0);
 
            Object[][] bookData = {
                    {target, date.toString(), formattedTime}
            };
 
            int rowCount = sheet.getLastRowNum();
            if (rowCount == 0){
                emptySheet = true;
            }
            else{
                emptySheet = false;
            }
            labelInfo.setText("RowCount is: "+rowCount);
            
            for (Object[] aBook : bookData) {
                //if (empty)
                Row row = sheet.createRow(rowCount);
                ++rowCount;
                
                int columnCount = 0;
                 
                org.apache.poi.ss.usermodel.Cell cell = row.createCell(columnCount);
                //cell.setCellValue(rowCount);
                 
                for (Object field : aBook) {
                    cell = row.createCell(columnCount);
                    ++columnCount;
                    if (field instanceof String) {
                        cell.setCellValue((String) field);
                    } else if (field instanceof Integer) {
                        cell.setCellValue((Integer) field);
                    }
                }
            }
            inputStream.close();
            FileOutputStream outputStream = new FileOutputStream(path);
            workbook.write(outputStream);
            workbook.close();
            outputStream.close();
             
        } catch (IOException | EncryptedDocumentException
                | InvalidFormatException ex) {
            ex.printStackTrace();
        }
        //labelInfo.setText("<html>Transfer time is successfully stored in:<br><i>"+path+"</i></html>");
        
        }
        else
            textPaneElapsedTime.setText("");
    }//GEN-LAST:event_stopButtonMousePressed

    private void menuBarFileItemBrowsefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarFileItemBrowsefileActionPerformed
        int returnVal = fileBrowser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File fileLocal = fileBrowser.getSelectedFile();
            file = fileLocal;
            path = file.toString();
        } else {
            System.out.println("File access cancelled by user.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarFileItemBrowsefileActionPerformed

    private void menuBarFileAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarFileAboutActionPerformed
        new About(this).setVisible(true);
    }//GEN-LAST:event_menuBarFileAboutActionPerformed

    private void jCheckBoxT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxT1ActionPerformed
        target = "T1";
    }//GEN-LAST:event_jCheckBoxT1ActionPerformed

    private void jCheckBoxT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxT2ActionPerformed
        target = "T2";
    }//GEN-LAST:event_jCheckBoxT2ActionPerformed

    private void jCheckBoxT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxT4ActionPerformed
        target = "T4";
    }//GEN-LAST:event_jCheckBoxT4ActionPerformed

    private void jCheckBoxEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEmptyActionPerformed
        target = "";
    }//GEN-LAST:event_jCheckBoxEmptyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuklidTransferTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuklidTransferTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuklidTransferTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuklidTransferTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuklidTransferTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCheckBox;
    private javax.swing.ButtonGroup buttonGroupStartStop;
    private javax.swing.JFileChooser fileBrowser;
    private javax.swing.JCheckBox jCheckBoxEmpty;
    private javax.swing.JCheckBox jCheckBoxT1;
    private javax.swing.JCheckBox jCheckBoxT2;
    private javax.swing.JCheckBox jCheckBoxT4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBarFile;
    private javax.swing.JMenuItem menuBarFileAbout;
    private javax.swing.JMenuItem menuBarFileItemBrowsefile;
    private javax.swing.JToggleButton startButton;
    private javax.swing.JToggleButton stopButton;
    private javax.swing.JTextPane textPaneElapsedTime;
    // End of variables declaration//GEN-END:variables
    DecimalFormat numberFormat = new DecimalFormat("#.00");


}
